datasets:
  - 20260615_site1
  - 20260615_site10

validation_config: 
    site10_original:
      constraint_selection:
        - - dataset
          - - 20260615_site10
      constraint_rejection: []

    site10_Const_pos_offset_low:
      constraint_selection:
        - - dataset
          - - 20260615_site10_const_pos_offset_low
      constraint_rejection: []

    site10_Random_pos_offset_low:
      constraint_selection:
        - - dataset
          - - 20260615_site10_random_pos_offset_low
      constraint_rejection: []
    
    site10_Random_pos_offset_median:
          constraint_selection:
            - - dataset
              - - 20260615_site10_random_pos_offset_median
          constraint_rejection: []
    
    site10_Random_pos_offset_high:
          constraint_selection:
            - - dataset
              - - 20260615_site10_random_pos_offset_high
          constraint_rejection: []
    
    site10_Random_pos_offset_road_constraint:
          constraint_selection:
            - - dataset
              - - 20260615_site10_random_pos_offset_low_road_constraint
          constraint_rejection: []
    
    site10_Random_pos_offset_randomTime_delay:
          constraint_selection:
            - - dataset
              - - 20260615_site10_random_pos_offset_low_randomTime_delay
          constraint_rejection: []



sets_norm_scale:
  - r2_set_0
  - r2_set_1
  - r2_set_2
  - r2_set_3
  - r2_set_4


sets_cv_exp:
  - r2_set_0
  - r2_set_1
  - r2_set_2
  - r2_set_3
  - r2_set_4

  
Components_config:
  DenseAE: config/config_ae.yaml
  DenseVAE: config/config_vae.yaml
  ConvAE: config/config_ae.yaml
  ConvVAE: config/config_vae.yaml
  TimeAE: config/config_ae.yaml
  TimeVAE: config/config_vae.yaml


context_features:
  ['id','timestamp','positionX','positionY','positionZ','sizeX','sizeY','sizeZ','VelX','VelY','VelZ','Vel','Class','rot_x','rot_y','edge',
  'ts','departure','destination','attacked','window','dataset','set','filename','seqId','length','cat_attack','cat_zone','cat_length']