datasets:
  - new_dataset10

validation_config:

    Const_pos_offset_low:
      constraint_selection:
        - - dataset
          - - new_dataset10_const_pos_offset
      constraint_rejection: []

    Random_pos_offset_low:
      constraint_selection:
        - - dataset
          - - new_dataset10_random_pos_offset_low
      constraint_rejection: []
    
    Random_pos_offset_median:
          constraint_selection:
            - - dataset
              - - new_dataset10_random_pos_offset_median
          constraint_rejection: []
    
    Random_pos_offset_high:
          constraint_selection:
            - - dataset
              - - new_dataset10_random_pos_offset_high
          constraint_rejection: []
    
    Random_pos_offset_road_constraint:
          constraint_selection:
            - - dataset
              - - new_dataset10_random_pos_offset_road_constraint
          constraint_rejection: []
    
    Random_pos_offset_randomTime_delay:
          constraint_selection:
            - - dataset
              - - new_dataset10_random_pos_offset_randomTime_delay
          constraint_rejection: []


sets_norm_scale:
  - r1_set_0
  - r1_set_1
  - r1_set_2
  - r1_set_3
  - r1_set_4
  # - r2_set_0
  # - r2_set_1
  # - r2_set_2
  # - r2_set_3
  # - r2_set_4
  # - set_0
  # - set_1
  # - set_2
  # - set_3
  # - set_4


sets_cv_exp:
  - r1_set_0
  - r1_set_1
  - r1_set_2
  - r1_set_3
  - r1_set_4
  # - r2_set_0
  # - r2_set_1
  # - r2_set_2
  # - r2_set_3
  # - r2_set_4
  # - set_0
  # - set_1
  # - set_2
  # - set_3
  # - set_4

  
Components_config:
  DenseAE: config/config_ae.yaml
  DenseVAE: config/config_vae.yaml
  ConvAE: config/config_ae.yaml
  ConvVAE: config/config_vae.yaml
  TimeAE: config/config_ae.yaml
  TimeVAE: config/config_vae.yaml